### ISSUE TITLE
Only preserve `cells`.

### ISSUE THREAD

**Issue by yasirroni** [srstevenson/nb-clean#157]
What do you think about only preserve `cells`? It means that it will clean all except 'cells`?

In the notebook example, it will destroy:

```
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:Python3] *",
   "language": "python",
   "name": "conda-env-Python3-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
 ```

**Comment by yasirroni** [comment]
Maybe option `--remove-non-cells`?

If you are interested, I might be able to help. Thanks.

**Comment by yasirroni** [comment]
This is the target notebooks.

https://github.com/yasirroni/nb-clean/blob/remove_non_cells/tests/notebooks/clean_only_cells.ipynb
___
The bare minimum that I found for notebook to be able to be rendered is:

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Hello, world\")"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by srstevenson** [comment]
`metadata`, `nbformat` and `nbformat_minor` must remain as they're required fields as per [the schema](https://github.com/jupyter/nbformat/blob/7e28474d618baf9889e609bcbfe64263337702e5/nbformat/v4/nbformat.v4.schema.json#L6).

I'd prefer we expressed this as `--remove-{thing to remove}` rather than `--remove-non-{thing to keep}` as it composes better with existing options, and is more robust to changes to the notebook schema in future which add additional fields.

**Comment by yasirroni** [comment]
Then, we can make it simple by cleaning the contents of `metadata`. About the nbformat and nbformat_minor, I don't know the best default value for all. Maybe shouldn't touch it for now.

The conclusion then, support `--remove-notebook-metadata`, making it `{}`.

**Comment by yasirroni** [comment]
> `nbformat` and `nbformat_minor` shouldn't be mutated. When [we read the notebook](https://github.com/srstevenson/nb-clean/blob/5ddf4f785d614a2d8d37aa47a07b48d474a13787/src/nb_clean/cli.py#L144) with [`nbformat.read`](https://nbformat.readthedocs.io/en/latest/api.html#nbformat.read), we pass `version=nbformat.NO_CONVERT` to prevent version conversion.

Agreed.

So, do you support if I add clean metadata? Because it seems not yet supported.

`--remove-notebook-metadata` make `metadata` value `{}`.

**Comment by haplav** [comment]
This is an issue also for me. It seems that no contents of `metadata` are mandatory per schema.

E.g. `/metadata/kernelspec/display_name` may get changed easily even on the same system. So it's very disturbing to have such data versioned.

I use VS Code and it also dumps
```
 "metadata": {
  ...
  "vscode": {
   "interpreter": {
    "hash": "<some_hash_string>"
   }
  }
 }
```
into `/metadata`.
Also a good candidate for filtering.

Alternatively (or additionally), nb-clean could perhaps be even more flexible and support e.g. [YAML paths](https://github.com/wwkimball/yamlpath). So that one could specify e.g. `nb-convert --remove-path=/metadata/vscode` or something like that.

**Comment by yasirroni** [comment]
Hi @haplav, I implement `--remove-notebook-metadata` in https://github.com/srstevenson/nb-clean/pull/169.

But, after I'm using nbQA, I think the best approach is to add:

```json
 "metadata": {
  "language_info": {
   "name": "python"
  }
```

Do you have any suggestion to improve that PR? Thank you,
