### ISSUE TITLE
[BUG] Filtering to ignore metadata during checks not working as expected

### ISSUE THREAD

**Issue by DanielTsiang** [srstevenson/nb-clean#252]
### Problem

Using the current latest versions of `nb-clean` i.e. `3.2.0`, it fails to ignore the following when checking the notebook even though it is configured to ignore it:
```shell
metadata: language_info.version
```

### Examples
When checking notebook:
```shell
$ nb-clean check my-notebook.ipynb 
my-notebook.ipynb metadata: language_info.version
```

#### Not working as expected
I thought `nb-clean` should no longer complain about the language info version metadata, but it still does:

```shell
$ nb-clean check my-notebook.ipynb -m/--preserve-cell-metadata 
my-notebook.ipynb metadata: language_info.version
```

```shell
$ nb-clean check my-notebook.ipynb -m/--preserve-notebook-metadata
my-notebook.ipynb metadata: language_info.version
```

```shell
$ nb-clean add-filter --preserve-cell-metadata
$ nb-clean check my-notebook.ipynb
my-notebook.ipynb metadata: language_info.version

$ nb-clean remove-filter
$ nb-clean add-filter --preserve-notebook-metadata
$ nb-clean check my-notebook.ipynb
my-notebook.ipynb metadata: language_info.version
```

```shell
$ nb-clean add-filter --preserve-notebook-metadata check my-notebook.ipynb
usage: nb-clean [-h] {version,add-filter,remove-filter,check,clean} ...
nb-clean: error: unrecognized arguments: check my-notebook.ipynb
```

#### Working as desired
Although this is not in the README.md, this is the only way I could get it to work as I desired, i.e. ignore the language info version metadata:

```shell
$ nb-clean add-filter --preserve-cell-metadata check my-notebook.ipynb 
$ echo $?
0
```

### Update
Turns out I misunderstood the README, it wasn't obvious to me that it was saying I could use the shorthand or the longhand of the flags. So this does work.

```shell
$ nb-clean check my-notebook.ipynb --preserve-notebook-metadata
$ echo $?
0
```

I would suggest modifying the README to include only the longhand (or shorthand) flags in the table, to avoid similar future confusion.

Also, there is a copy-paste typo for ignoring notebook metadata, i.e. it incorrectly copied the values from the cell metadata.

![Screenshot 2024-01-17 at 14 28 05](https://github.com/srstevenson/nb-clean/assets/74436899/b0642c3d-54c5-40f8-a467-663b4f85ee4e)

**Comment by srstevenson** [comment]
To ignore metadata such as `language_info.version` when checking or cleaning a notebook, you should use the `--preserve-notebook-metadata` flag, rather than `--preserve-cell-metadata`, as this is metadata present at the top-level of the notebook rather than attached to an individual cell. The short flag equivalent to `--preserve-notebook-metadata` is `-n`, which you can use instead: but you don't need to pass both `-n` and `--preserve-notebook-metadata`.

There are a couple of other things to note:
- you can only pass a single subcommand when you run nb-clean, which is why your example of `nb-clean add-filter --preserve-notebook-metadata check my-notebook.ipynb` doesn't work: if you want to install the Git filter _and_ check a notebook in the working copy, you need to run two separate commands:
  ```
  $ nb-clean add-filter --preserve-notebook-metadata
  $ nb-clean check --preserve-notebook-metadata my-notebook.ipynb
  ```
- running nb-clean at the command line respects the flags passed to that call and doesn't use flags from the Git filter if you've installed it. This means in the example below that although the Git filter is configured to preserve cell metadata, the `check` command isn't unless you also pass `--preserve-cell-metadata` there.
  ```
  $ nb-clean add-filter --preserve-cell-metadata
  $ nb-clean check my-notebook.ipynb  # does not preserve cell metadata
  ```

The `-f`/`--foo` syntax in the README to document the short and long alternatives for each flag isn't as clear as saying `-f` or `--foo`: thanks for improving this in your PR!
