### ISSUE TITLE
[BUG] Using preserve cell metadata flag before filename not working as expected

### ISSUE THREAD

**Issue by DanielTsiang** [srstevenson/nb-clean#255]
### Problem

Using the current latest versions of `nb-clean` i.e. `3.2.0`, checking the notebook with preserving the cell metadata flag before the filename causes the command to hang indefinitely.

#### Working as expected

```shell
$ nb-clean check notebook.ipynb --preserve-cell-metadata
notebook.ipynb metadata: language_info.version
```

#### Not working as expected
These just hang and it never finishes the commands:

```shell
$ nb-clean check --preserve-cell-metadata notebook.ipynb 
```

```shell
$ nb-clean check --preserve-notebook-metadata --preserve-cell-metadata notebook.ipynb 
```

#### Other working examples

These commands also work as expected:

```shell
$ nb-clean check --preserve-notebook-metadata notebook.ipynb
notebook cell 12: metadata
```

```shell
$ nb-clean check notebook.ipynb --preserve-notebook-metadata
notebook cell 12: metadata
```

```shell
$ nb-clean check notebook.ipynb --preserve-cell-metadata --preserve-notebook-metadata
$ echo $?
0
```

**Comment by srstevenson** [comment]
This is an interesting case!

`--preserve-cell-metadata` isn't a boolean flag like `--preserve-notebook-metadata`: whereas `--preserve-notebook-metadata` takes no arguments, `--preserve-cell-metadata` can take a list of metadata fields to be preserved such as:
```
$ nb-clean clean notebook.ipynb --preserve-cell-metadata tags special
```
In this case, the `tags` and `special` fields will be preserved, but any others will be removed. If you don't pass any arguments to `--preserve-cell-metadata`, all cell metadata fields are removed:
```
$ nb-clean clean notebook.ipynb --preserve-cell-metadata
```
However, because `--preserve-cell-metadata` can take zero or more arguments, the argument parser assigns any positional arguments following this flag as fields to preserve rather than notebook paths to process--it can't tell the difference. It then hangs as it's waiting to receive the notebook contents on standard input. You can try this out by piping in the notebook contents, and seeing that it now executes immediately:
```
$ nb-clean check --preserve-cell-metadata notebook.ipynb < notebook.ipynb
stdin metadata: language_info.version
```
In practice, this means if you're not passing any custom fields to preserve, the `--preserve-cell-metadata` flag needs to appear _after_ the paths to be processed, as you found here.

**Comment by srstevenson** [comment]
I'll close this now, as we added documentation about it in #254.

**Comment by DanielTsiang** [comment]
That makes sense, thanks for explaining and amending the documentation!

For future reference, this is also a possible alternative if the user wishes to keep `--preserve-cell-metadata` at the end of the piped `xargs` command in the CI:

```bash
echo  "file 1\nfile 2\nfile 3" | xargs -L1 -I {} nb-clean check "{}" --preserve-notebook-metadata --preserve-cell-metadata
```
